# crypto_symbols.py

crypto_symbols = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "SOLUSDT", "ADAUSDT", "DOGEUSDT", "TRXUSDT", "LINKUSDT",
    "MATICUSDT", "DOTUSDT", "LTCUSDT", "SHIBUSDT", "AVAXUSDT", "XLMUSDT", "TONUSDT", "ATOMUSDT", "UNIUSDT",
    "ETCUSDT", "FILUSDT", "HBARUSDT", "APTUSDT", "LDOUSDT", "PIXELUSDT", "MKRUSDT", "AAVEUSDT", "OPUSDT",
    "NEARUSDT", "ARBUSDT", "INJUSDT", "GRTUSDT", "RNDRUSDT", "STXUSDT", "RUNEUSDT", "ALGOUSDT", "IMXUSDT",
    "AXSUSDT", "EGLDUSDT", "SANDUSDT", "MANAUSDT", "XTZUSDT", "THETAUSDT", "FTMUSDT", "NEOUSDT", "SNXUSDT",
    "MINAUSDT", "KAVAUSDT", "FLOWUSDT", "CFXUSDT", "APEUSDT", "CHZUSDT", "GALAUSDT", "PEPEUSDT", "IOTAUSDT",
    "DYDXUSDT", "FXSUSDT", "TWTUSDT", "CRVUSDT", "KLAYUSDT", "GMXUSDT", "WOOUSDT", "SUIUSDT", "COMPUSDT",
    "FLOKIUSDT", "ARUSDT", "GASUSDT", "LOOMUSDT", "TRBUSDT", "ARKUSDT", "POLYXUSDT", "FETUSDT", "UNFIUSDT",
    "BLZUSDT", "AIUSDT", "ARKMUSDT", "RLCUSDT", "WLDUSDT", "JUPUSDT", "MANTAUSDT", "BLURUSDT", "FRONTUSDT",
    "PEOPLEUSDT", "UMAUSDT", "HIGHUSDT", "API3USDT", "BMTUSDT", "FISUSDT", "SIRENUSDT", "PENGUUSDT", "WALUSDT",
    "MEMEFIUSDT", "DEEPUSDT", "VVVUSDT", "FLMUSDT", "HEIUSDT", "ALCHUSDT", "FARTCOINUSDT", "1000BONKUSDT",
    "AI16ZUSDT", "HIPPOUSDT", "TRUMPUSDT", "VIRTUALUSDT", "FISUSDT", "TURBOUSDT", "ENAUSDT", "ONDOUSDT",
    "HYPERUSDT", "JELLYJELLYUSDT", "AIXBTUSDT", "MUBARAKUSDT", "GUNUSDT", "POPCATUSDT", "ZEREBROUSDT",
    "PNUTUSDT", "BROCCOLI714USDT", "MOODENGUSDT"
]
